### ISSUE TITLE
Suggestion: Add docs on how docs are being built

### ISSUE THREAD

**Issue by sappelhoff** [JanCBrammer/biopeaks#10]
related to JOSS review (https://github.com/openjournals/joss-reviews/issues/2621)

I think it'd be helpful for potential contributors (or your future self) to have a short paragraph with information on how the documentation is being build and deployed. A good place for this documentation would be in the contributors guide.

**Comment by sappelhoff** [comment]
another note: when adding docs on how to build docs, perhaps it'd be worth adding also docs for contributors on how to install a "development version" of the repository (which is required for making PRs)

**Comment by JanCBrammer** [comment]
@sappelhoff, see f2d61019eb9c59ebc253707f38d3dfc025276aa0.

**Comment by sappelhoff** [comment]
looks good to me, thanks!
