### ISSUE TITLE
Discussion: Adopting a consistent style for docstrings

### ISSUE THREAD

**Issue by sappelhoff** [JanCBrammer/biopeaks#11]
related to JOSS review (https://github.com/openjournals/joss-reviews/issues/2621)

Looking at the code base, I find functions / methods / classes that are sometimes not documented, and sometimes extensively documented but in a seemingly unstructured way. Sometimes I also see a documentation about function parameters such as here:

https://github.com/JanCBrammer/biopeaks/blob/89fe7c8c80de29549951e6f7fed75fb21506903a/biopeaks/benchmarks/benchmark_utils.py#L17-L19

but more often than not, the parameters are not documented.

**I would strongly recommend to adopt a consistent docstr style** (such as [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html)) **and apply this to the codebase**. The style can also be enforced with `flake8` extensions such as  [`flake8-docstrings`](https://pypi.org/project/flake8-docstrings/).

Consistent, extensive (but concise) docstrings make life easier for contributors, reviewers, and your future self ... and perhaps also for users --> but for that last part I am not entirely sure, because this a GUI package after all, and users are not expected to work with an API.

That latter sentence is the reason why I label this issue as "Discussion" ... I can imagine that other people have different opinions about this point.

**Comment by sappelhoff** [comment]
Documentation with docstrings for me also includes writing an "introductory docstring" for **each** public module (almost every .py file).

For example the `benchmark_ECG_stream.py` file looks like this:

```Python
from biopeaks.heart import ecg_peaks
from benchmark_utils import BenchmarkDetectorGUDB


pipeline = BenchmarkDetectorGUDB(ecg_peaks, 1)
pipeline.benchmark_records("jogging", channel="cs_V2_V1", annotation="annotation_cs")

```

But I  think it should look like the following.

(Note 1: and Python docstring convention also thinks that way :slightly_smiling_face: see pep [257](https://www.python.org/dev/peps/pep-0257/) and the D100 error flake8 gives you when you don't write a module level docstring)

(Note 2: the *content* of the docstr is made up, just as an example)


```Python
"""Benchmark the ECG algorithm against the database.

Here we stream data from XYZ and feed it through our algorithm.
Important resources to check are: http.I.like.it

"""
from biopeaks.heart import ecg_peaks
from benchmark_utils import BenchmarkDetectorGUDB


pipeline = BenchmarkDetectorGUDB(ecg_peaks, 1)
pipeline.benchmark_records("jogging", channel="cs_V2_V1", annotation="annotation_cs")

```

**Comment by TomDonoghue** [comment]
I totally agree on this point - I think picking and applying a consistent documentation structure would help the codebase a fair amount. It is true that the average user might not see this (since it's a GUI), but under the assumption that this is a tool to be supported for a while, the documentation is for maintainers (including you in the future). I reckon it will be much easier to learn whats going on with nice in-code documentation, and this would help a lot with onboarding (right now, just scrolling through the code, it's harder to get a sense of how things work). 

Note: I'm also from the JOSS review

**Comment by JanCBrammer** [comment]
@sappelhoff, @TomDonoghue, all modules, classes/methods, and functions are now documented according to [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) conventions. I agree that this is necessary and useful, despite `biopeaks` mostly containing GUI code.

**Comment by sappelhoff** [comment]
great, I see many docstr improvements! Thanks :-)
