### ISSUE TITLE
Questions about the default method of ecg_peaks() in neurokit2

### ISSUE THREAD

**Issue by skywalkerzhang** [JanCBrammer/biopeaks#23]
Hi, I am a university student at the University of Manchester that working on my dissertation now. I have used the library that you are participated in(neurokit2).

Dominique told me that you had written the default method of ecg_peaks() if you could tell me the general idea about your method(A paper would be the best) used for my method part in my dissertation(I mean, it's your method, I will mention that and cite the citations of the biopeaks and neurokit2). 

However, if you haven't plan to make your default method public, could you please tell me about that to change another method.

English is not my mother tongue, so I hope you don't mind if I offend you. Thank you for your contribution to open source.

**Comment by JanCBrammer** [comment]
Hi @skywalkerzhang, thanks for your question. Have a look at https://joss.theoj.org/papers/10.21105/joss.02621. In the paper there's a validation of the R-peak detector that was originally implemented for `biopeaks` and is now also used as default method for R-peak detection in `NeuroKit2`. Note that the paper doesn't include details on the internals of the algorithm, only a validation, but maybe it can still be useful as a reference.

You can have a look at the implementation here:
https://github.com/JanCBrammer/biopeaks/blob/9d11af41cb9a2b11baf7a53e70a08ffc54ec4152/biopeaks/heart.py#L14-L104

Maybe visualizing the R-peak detection by calling the function with `enable_plot=True` can give you some more insight in how the detection works.
